# coding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
ActiveRecord::Base.connection.execute "INSERT INTO categories (name, created_at, updated_at) VALUES ('(Sub-)Surface Sensing Technologies and Systems', current_timestamp, current_timestamp),
('Accounting', current_timestamp, current_timestamp),
('Acoustics, Speech and Signal Processing', current_timestamp, current_timestamp),
('Actuarial Studies', current_timestamp, current_timestamp),
('Adapted Physical Activity', current_timestamp, current_timestamp),
('Aeronautics', current_timestamp, current_timestamp),
('Aerospace Engineering', current_timestamp, current_timestamp),
('Africa', current_timestamp, current_timestamp),
('Agricultural Economics', current_timestamp, current_timestamp),
('Agricultural Science', current_timestamp, current_timestamp),
('AIDS', current_timestamp, current_timestamp),
('Air and Space Law', current_timestamp, current_timestamp),
('Alcoholism and Addiction', current_timestamp, current_timestamp),
('Algebra', current_timestamp, current_timestamp),
('Algology', current_timestamp, current_timestamp),
('Algorithms and Computational Theory', current_timestamp, current_timestamp),
('Allergy', current_timestamp, current_timestamp),
('Analysis', current_timestamp, current_timestamp),
('Analytical Chemistry', current_timestamp, current_timestamp),
('Anesthesiology', current_timestamp, current_timestamp),
('Animal Behavior', current_timestamp, current_timestamp),
('Animal Physiology', current_timestamp, current_timestamp),
('Antennas and Propagation', current_timestamp, current_timestamp),
('Anthropology', current_timestamp, current_timestamp),
('Applied Chemistry', current_timestamp, current_timestamp),
('Applied Linguistics', current_timestamp, current_timestamp),
('Applied Probability', current_timestamp, current_timestamp),
('Archaeology', current_timestamp, current_timestamp),
('Architecture', current_timestamp, current_timestamp),
('Art History', current_timestamp, current_timestamp),
('Arthritis', current_timestamp, current_timestamp),
('Artificial Intelligence', current_timestamp, current_timestamp),
('Arts and Literature', current_timestamp, current_timestamp),
('Assessment and Evaluation', current_timestamp, current_timestamp),
('Asthma', current_timestamp, current_timestamp),
('Astronomy / Astrophysics / Space Science', current_timestamp, current_timestamp),
('Atmospheric Sciences', current_timestamp, current_timestamp),
('Atomic and Molecular Physics', current_timestamp, current_timestamp),
('Automobiles', current_timestamp, current_timestamp),
('Banks and Banking', current_timestamp, current_timestamp),
('Bible', current_timestamp, current_timestamp),
('Biochemistry', current_timestamp, current_timestamp),
('Biodegradation', current_timestamp, current_timestamp),
('Bioinformatics', current_timestamp, current_timestamp),
('Biological Sciences', current_timestamp, current_timestamp),
('Biomedical Engineering', current_timestamp, current_timestamp),
('Biomedical Physics', current_timestamp, current_timestamp),
('Biometry', current_timestamp, current_timestamp),
('Biophysics', current_timestamp, current_timestamp),
('Biotechnology', current_timestamp, current_timestamp),
('Botany', current_timestamp, current_timestamp),
('Buddhism', current_timestamp, current_timestamp),
('Business Administration', current_timestamp, current_timestamp),
('Business Education', current_timestamp, current_timestamp),
('Business, Commercial, Consumer and Financial Law', current_timestamp, current_timestamp),
('Cancer', current_timestamp, current_timestamp),
('Cardiology', current_timestamp, current_timestamp),
('Catholicism', current_timestamp, current_timestamp),
('Celestial Mechanics', current_timestamp, current_timestamp),
('Cellular Biology', current_timestamp, current_timestamp),
('Cement', current_timestamp, current_timestamp),
('Ceramics', current_timestamp, current_timestamp),
('Chemical Engineering', current_timestamp, current_timestamp),
('Chemical Physics', current_timestamp, current_timestamp),
('Chemistry', current_timestamp, current_timestamp),
('Child Abuse', current_timestamp, current_timestamp),
('Child Behavior', current_timestamp, current_timestamp),
('Child Literature', current_timestamp, current_timestamp),
('Christianity', current_timestamp, current_timestamp),
('Chromatography', current_timestamp, current_timestamp),
('Church', current_timestamp, current_timestamp),
('Circuits and Systems', current_timestamp, current_timestamp),
('Civil Engineering', current_timestamp, current_timestamp),
('Clinical and Counselling Psychology', current_timestamp, current_timestamp),
('Clinical Molecular and Microbiology', current_timestamp, current_timestamp),
('Cognition', current_timestamp, current_timestamp),
('Cognitive Psychology', current_timestamp, current_timestamp),
('Communication Design', current_timestamp, current_timestamp),
('Communication Disorders', current_timestamp, current_timestamp),
('Communication', current_timestamp, current_timestamp),
('Community and Environmental Psychology', current_timestamp, current_timestamp),
('Comparative Education', current_timestamp, current_timestamp),
('Comparative Law', current_timestamp, current_timestamp),
('Computational Linguistics', current_timestamp, current_timestamp),
('Computational Physics', current_timestamp, current_timestamp),
('Computer and Information Science', current_timestamp, current_timestamp),
('Computer Architecture', current_timestamp, current_timestamp),
('Computer Law, Intellectual Property and Media Law', current_timestamp, current_timestamp),
('Computer Security', current_timestamp, current_timestamp),
('Condensed Matter Physics', current_timestamp, current_timestamp),
('Constitutional Law', current_timestamp, current_timestamp),
('Construction', current_timestamp, current_timestamp),
('Control and Optimization', current_timestamp, current_timestamp),
('Control Systems', current_timestamp, current_timestamp),
('Cosmology', current_timestamp, current_timestamp),
('Counselling', current_timestamp, current_timestamp),
('Criminology', current_timestamp, current_timestamp),
('Cross Cultural Psychology', current_timestamp, current_timestamp),
('Crystallography', current_timestamp, current_timestamp),
('Cultural Economics', current_timestamp, current_timestamp),
('Culture Heritage', current_timestamp, current_timestamp),
('Curriculum Studies', current_timestamp, current_timestamp),
('Data Communication and Networks', current_timestamp, current_timestamp),
('Database Systems', current_timestamp, current_timestamp),
('Decision Analysis', current_timestamp, current_timestamp),
('Demography', current_timestamp, current_timestamp),
('Dentistry and Oral Surgery', current_timestamp, current_timestamp),
('Depression', current_timestamp, current_timestamp),
('Dermatology', current_timestamp, current_timestamp),
('Design Automation', current_timestamp, current_timestamp),
('Design', current_timestamp, current_timestamp),
('Developmental Psychology', current_timestamp, current_timestamp),
('Discrete Mathematics', current_timestamp, current_timestamp),
('Drug Abuse', current_timestamp, current_timestamp),
('Earth Sciences', current_timestamp, current_timestamp),
('Earth-Surface Processes', current_timestamp, current_timestamp),
('Ecology', current_timestamp, current_timestamp),
('Econometrics', current_timestamp, current_timestamp),
('Economic Development, Technological Change and Growth', current_timestamp, current_timestamp),
('Economic Geology', current_timestamp, current_timestamp),
('Economic Law', current_timestamp, current_timestamp),
('Economic Systems', current_timestamp, current_timestamp),
('Economics History', current_timestamp, current_timestamp),
('Economics', current_timestamp, current_timestamp),
('Education Research', current_timestamp, current_timestamp),
('Education', current_timestamp, current_timestamp),
('Educational Administration', current_timestamp, current_timestamp),
('Educational Change', current_timestamp, current_timestamp),
('Educational Psychology', current_timestamp, current_timestamp),
('Educational Technology', current_timestamp, current_timestamp),
('Electrical and Electronic Engineering', current_timestamp, current_timestamp),
('Electron Devices', current_timestamp, current_timestamp),
('Electronic Commerce', current_timestamp, current_timestamp),
('Electronic Publishing', current_timestamp, current_timestamp),
('Embryology', current_timestamp, current_timestamp),
('Emergency Medicine and Critical Care', current_timestamp, current_timestamp),
('Employment and Social Security Law', current_timestamp, current_timestamp),
('Endocrinology', current_timestamp, current_timestamp),
('Energy and Natural Resources Law', current_timestamp, current_timestamp),
('Energy', current_timestamp, current_timestamp),
('Engineering', current_timestamp, current_timestamp),
('English Language', current_timestamp, current_timestamp),
('Entertainment, Sports and Gaming Law', current_timestamp, current_timestamp),
('Entomology', current_timestamp, current_timestamp),
('Entrepreneurship', current_timestamp, current_timestamp),
('Environmental Biotechnology', current_timestamp, current_timestamp),
('Environmental Conservation', current_timestamp, current_timestamp),
('Environmental Economics', current_timestamp, current_timestamp),
('Environmental Engineering', current_timestamp, current_timestamp),
('Environmental Fluid Dynamics', current_timestamp, current_timestamp),
('Environmental Planning', current_timestamp, current_timestamp),
('Environmental Sciences', current_timestamp, current_timestamp),
('Environmental Toxicology', current_timestamp, current_timestamp),
('Environmental', current_timestamp, current_timestamp),
('Epidemiology', current_timestamp, current_timestamp),
('Epistemology', current_timestamp, current_timestamp),
('Ethics', current_timestamp, current_timestamp),
('Ethnology', current_timestamp, current_timestamp),
('European Community Law', current_timestamp, current_timestamp),
('Evolutionary Psychology', current_timestamp, current_timestamp),
('Experimental Psychology', current_timestamp, current_timestamp),
('Extragalactic Astronomy', current_timestamp, current_timestamp),
('Family Law', current_timestamp, current_timestamp),
('Family Therapy', current_timestamp, current_timestamp),
('Family', current_timestamp, current_timestamp),
('Fashion Design', current_timestamp, current_timestamp),
('Feminism', current_timestamp, current_timestamp),
('Film and TV Studies', current_timestamp, current_timestamp),
('Finance and Financial Services', current_timestamp, current_timestamp),
('Fisheries', current_timestamp, current_timestamp),
('Fitness, Training and Injury', current_timestamp, current_timestamp),
('Fluid Mechanics/Dynamics', current_timestamp, current_timestamp),
('Folklore', current_timestamp, current_timestamp),
('Food Science and Technology', current_timestamp, current_timestamp),
('Forestry Science', current_timestamp, current_timestamp),
('Foundations, Sets and Categories', current_timestamp, current_timestamp),
('French Language', current_timestamp, current_timestamp),
('Futurology', current_timestamp, current_timestamp),
('Game Theory', current_timestamp, current_timestamp),
('Gastroenterology and Hepatology', current_timestamp, current_timestamp),
('General Medicine', current_timestamp, current_timestamp),
('Genetics', current_timestamp, current_timestamp),
('Geochemistry', current_timestamp, current_timestamp),
('Geography', current_timestamp, current_timestamp),
('Geology', current_timestamp, current_timestamp),
('Geometry', current_timestamp, current_timestamp),
('Geophysics', current_timestamp, current_timestamp),
('Geotechnical Engineering', current_timestamp, current_timestamp),
('Geriatrics and Aging', current_timestamp, current_timestamp),
('German Language', current_timestamp, current_timestamp),
('Gerontology', current_timestamp, current_timestamp),
('Glass', current_timestamp, current_timestamp),
('Global Environmental Change', current_timestamp, current_timestamp),
('Graphic Design', current_timestamp, current_timestamp),
('Graphics', current_timestamp, current_timestamp),
('Groups', current_timestamp, current_timestamp),
('Gynecology', current_timestamp, current_timestamp),
('Health and Wellness', current_timestamp, current_timestamp),
('Health Law', current_timestamp, current_timestamp),
('Health Psychology/Behavioral Medicine', current_timestamp, current_timestamp),
('Hematology', current_timestamp, current_timestamp),
('High Energy Physics', current_timestamp, current_timestamp),
('Histology', current_timestamp, current_timestamp),
('Historical Linguistics', current_timestamp, current_timestamp),
('History of Medicine', current_timestamp, current_timestamp),
('History of Sport and Recreation', current_timestamp, current_timestamp),
('History', current_timestamp, current_timestamp),
('Human Resource Management', current_timestamp, current_timestamp),
('Human Rights', current_timestamp, current_timestamp),
('Human-Computer Interaction', current_timestamp, current_timestamp),
('Humanistic and Transpersonal Psychology', current_timestamp, current_timestamp),
('Humanities', current_timestamp, current_timestamp),
('Hydrobiology', current_timestamp, current_timestamp),
('Hydrology', current_timestamp, current_timestamp),
('Ichthyology', current_timestamp, current_timestamp),
('Image Processing', current_timestamp, current_timestamp),
('Immunology', current_timestamp, current_timestamp),
('Industrial and Engineering Chemistry', current_timestamp, current_timestamp),
('Industrial and Organizational Psychology', current_timestamp, current_timestamp),
('Industrial Design', current_timestamp, current_timestamp),
('Industrial Management', current_timestamp, current_timestamp),
('Industrial Relations', current_timestamp, current_timestamp),
('Information Retrieval', current_timestamp, current_timestamp),
('Information Science', current_timestamp, current_timestamp),
('Information Storage', current_timestamp, current_timestamp),
('Information Theory', current_timestamp, current_timestamp),
('Inorganic Chemistry', current_timestamp, current_timestamp),
('Insurance', current_timestamp, current_timestamp),
('Intellectual Property', current_timestamp, current_timestamp),
('Intelligence Testing', current_timestamp, current_timestamp),
('Internal Medicine', current_timestamp, current_timestamp),
('International Business', current_timestamp, current_timestamp),
('International Economics', current_timestamp, current_timestamp),
('International Law', current_timestamp, current_timestamp),
('Interstellar Matter', current_timestamp, current_timestamp),
('Islam', current_timestamp, current_timestamp),
('Judaism', current_timestamp, current_timestamp),
('Kinesiology', current_timestamp, current_timestamp),
('Language Education', current_timestamp, current_timestamp),
('Languages and Literature', current_timestamp, current_timestamp),
('Lasers and Electro-optics', current_timestamp, current_timestamp),
('Latin', current_timestamp, current_timestamp),
('Law and Economics', current_timestamp, current_timestamp),
('Law of the Sea/Maritime Law', current_timestamp, current_timestamp),
('Law', current_timestamp, current_timestamp),
('Legal Practice', current_timestamp, current_timestamp),
('Legal Theory', current_timestamp, current_timestamp),
('Library and Information Science', current_timestamp, current_timestamp),
('Limnology', current_timestamp, current_timestamp),
('Linguistics', current_timestamp, current_timestamp),
('Literature', current_timestamp, current_timestamp),
('Logic', current_timestamp, current_timestamp),
('Logistics', current_timestamp, current_timestamp),
('Macroeconomics', current_timestamp, current_timestamp),
('Management and Communication', current_timestamp, current_timestamp),
('Management and Marketing', current_timestamp, current_timestamp),
('Management and Strategy', current_timestamp, current_timestamp),
('Management Information Systems', current_timestamp, current_timestamp),
('Management Science / Operations Research', current_timestamp, current_timestamp),
('Management Science', current_timestamp, current_timestamp),
('Manufacturing Technology', current_timestamp, current_timestamp),
('Marine Biology', current_timestamp, current_timestamp),
('Marketing Research', current_timestamp, current_timestamp),
('Marketing', current_timestamp, current_timestamp),
('Mass Spectrometry', current_timestamp, current_timestamp),
('Materials Science', current_timestamp, current_timestamp),
('Materials Synthesis', current_timestamp, current_timestamp),
('Mathematical Economics', current_timestamp, current_timestamp),
('Mathematical Modelling and Industrial Mathematics', current_timestamp, current_timestamp),
('Mathematical Physics', current_timestamp, current_timestamp),
('Mathematical Programming', current_timestamp, current_timestamp),
('Mathematics Education', current_timestamp, current_timestamp),
('Mathematics', current_timestamp, current_timestamp),
('Mechanical Engineering', current_timestamp, current_timestamp),
('Media Studies', current_timestamp, current_timestamp),
('Medical Education', current_timestamp, current_timestamp),
('Medical Imaging', current_timestamp, current_timestamp),
('Medicine', current_timestamp, current_timestamp),
('Metallurgy', current_timestamp, current_timestamp),
('Metaphysics', current_timestamp, current_timestamp),
('Meteorology', current_timestamp, current_timestamp),
('Meteors', current_timestamp, current_timestamp),
('Methodology of Social Sciences', current_timestamp, current_timestamp),
('Microbiology', current_timestamp, current_timestamp),
('Microeconomics', current_timestamp, current_timestamp),
('Microprocessors', current_timestamp, current_timestamp),
('Microscopy', current_timestamp, current_timestamp),
('Mineralogy', current_timestamp, current_timestamp),
('Molecular Biology', current_timestamp, current_timestamp),
('Monetary Economics', current_timestamp, current_timestamp),
('Multimedia Systems and Applications', current_timestamp, current_timestamp),
('Music', current_timestamp, current_timestamp),
('Muslim', current_timestamp, current_timestamp),
('Mycology', current_timestamp, current_timestamp),
('Nanotechnology', current_timestamp, current_timestamp),
('Native Americans', current_timestamp, current_timestamp),
('Nephrology, Urology', current_timestamp, current_timestamp),
('Neural Networks', current_timestamp, current_timestamp),
('Neurobiology', current_timestamp, current_timestamp),
('Neurology', current_timestamp, current_timestamp),
('Neuroscience', current_timestamp, current_timestamp),
('Nuclear Engineering', current_timestamp, current_timestamp),
('Nuclear Magnetic Resonance', current_timestamp, current_timestamp),
('Nuclear Physics', current_timestamp, current_timestamp),
('Number Theory', current_timestamp, current_timestamp),
('Nursing', current_timestamp, current_timestamp),
('Nutrition and Metabolism', current_timestamp, current_timestamp),
('Obesity', current_timestamp, current_timestamp),
('Obstetrics', current_timestamp, current_timestamp),
('Occupational and Environmental', current_timestamp, current_timestamp),
('Occupational Therapy', current_timestamp, current_timestamp),
('Oceanography', current_timestamp, current_timestamp),
('Offshore Engineering', current_timestamp, current_timestamp),
('Oncology', current_timestamp, current_timestamp),
('Ontology', current_timestamp, current_timestamp),
('Operating Systems', current_timestamp, current_timestamp),
('Ophthalmology', current_timestamp, current_timestamp),
('Optics and Optoelectronics', current_timestamp, current_timestamp),
('Optometry', current_timestamp, current_timestamp),
('Organic Chemistry', current_timestamp, current_timestamp),
('Organizational Science', current_timestamp, current_timestamp),
('Ornithology', current_timestamp, current_timestamp),
('Orthopedics', current_timestamp, current_timestamp),
('Otolaryngology', current_timestamp, current_timestamp),
('Pain Medicine and Palliative Care', current_timestamp, current_timestamp),
('Paleontology', current_timestamp, current_timestamp),
('Paper Industry', current_timestamp, current_timestamp),
('Parapsychology', current_timestamp, current_timestamp),
('Parasitology', current_timestamp, current_timestamp),
('Pathology and Forensics', current_timestamp, current_timestamp),
('Pediatrics', current_timestamp, current_timestamp),
('Personality Psychology', current_timestamp, current_timestamp),
('Petroleum', current_timestamp, current_timestamp),
('Petrology', current_timestamp, current_timestamp),
('Pharmacology', current_timestamp, current_timestamp),
('Pharmacy', current_timestamp, current_timestamp),
('Phenomenology', current_timestamp, current_timestamp),
('Philology', current_timestamp, current_timestamp),
('Philosophy of Biology', current_timestamp, current_timestamp),
('Philosophy of Education', current_timestamp, current_timestamp),
('Philosophy of Language', current_timestamp, current_timestamp),
('Philosophy of Law', current_timestamp, current_timestamp),
('Philosophy of Medicine', current_timestamp, current_timestamp),
('Philosophy of Mind', current_timestamp, current_timestamp),
('Philosophy of Religion', current_timestamp, current_timestamp),
('Philosophy of Science', current_timestamp, current_timestamp),
('Philosophy of Technology', current_timestamp, current_timestamp),
('Philosophy of the Social Sciences', current_timestamp, current_timestamp),
('Philosophy', current_timestamp, current_timestamp),
('Phonetics', current_timestamp, current_timestamp),
('Photochemistry', current_timestamp, current_timestamp),
('Physical Chemistry', current_timestamp, current_timestamp),
('Physical Education', current_timestamp, current_timestamp),
('Physics Education Research', current_timestamp, current_timestamp),
('Physics', current_timestamp, current_timestamp),
('Physiology', current_timestamp, current_timestamp),
('Physiotherapy', current_timestamp, current_timestamp),
('Plant Sciences', current_timestamp, current_timestamp),
('Plastics', current_timestamp, current_timestamp),
('Political Economics', current_timestamp, current_timestamp),
('Political Psychology', current_timestamp, current_timestamp),
('Political Science', current_timestamp, current_timestamp),
('Pollution', current_timestamp, current_timestamp),
('Polymer Chemistry', current_timestamp, current_timestamp),
('Postmodernism', current_timestamp, current_timestamp),
('Power Systems', current_timestamp, current_timestamp),
('Private, Civil, Criminal Law and Litigation', current_timestamp, current_timestamp),
('Probability', current_timestamp, current_timestamp),
('Processes', current_timestamp, current_timestamp),
('Production, Operations and Manufacturing Management', current_timestamp, current_timestamp),
('Professional Sports', current_timestamp, current_timestamp),
('Programming Languages', current_timestamp, current_timestamp),
('Properties', current_timestamp, current_timestamp),
('Property Law', current_timestamp, current_timestamp),
('Psychiatry', current_timestamp, current_timestamp),
('Psychoanalysis', current_timestamp, current_timestamp),
('Psycholinguistics', current_timestamp, current_timestamp),
('Psychology and Law', current_timestamp, current_timestamp),
('Psychology', current_timestamp, current_timestamp),
('Psychopharmacology', current_timestamp, current_timestamp),
('Psychotherapy', current_timestamp, current_timestamp),
('Public and Non-Profit Management', current_timestamp, current_timestamp),
('Public Economics', current_timestamp, current_timestamp),
('Public Health and Community Medicine', current_timestamp, current_timestamp),
('Public Opinion', current_timestamp, current_timestamp),
('Public Welfare', current_timestamp, current_timestamp),
('Quality Control', current_timestamp, current_timestamp),
('Quantitative Methods', current_timestamp, current_timestamp),
('Queer Studies', current_timestamp, current_timestamp),
('Radiation', current_timestamp, current_timestamp),
('Radiochemistry', current_timestamp, current_timestamp),
('Radioisotopes', current_timestamp, current_timestamp),
('Railroads', current_timestamp, current_timestamp),
('Real-Time Systems', current_timestamp, current_timestamp),
('Recreation and Leisure', current_timestamp, current_timestamp),
('Regional and Cultural Studies', current_timestamp, current_timestamp),
('Regional Economics', current_timestamp, current_timestamp),
('Regional Law', current_timestamp, current_timestamp),
('Rehabilitation', current_timestamp, current_timestamp),
('Reliability and Risk Analysis', current_timestamp, current_timestamp),
('Religion', current_timestamp, current_timestamp),
('Remote Sensing/Photogrammetry', current_timestamp, current_timestamp),
('Reproductive Medicine', current_timestamp, current_timestamp),
('Respiratory and Pulmonary', current_timestamp, current_timestamp),
('Rheumatology', current_timestamp, current_timestamp),
('Robotics and Automation', current_timestamp, current_timestamp),
('Rubber', current_timestamp, current_timestamp),
('Rural Development', current_timestamp, current_timestamp),
('Schizophrenia', current_timestamp, current_timestamp),
('Science Education', current_timestamp, current_timestamp),
('Sedimentology', current_timestamp, current_timestamp),
('Seismology/Seismics', current_timestamp, current_timestamp),
('Semantics', current_timestamp, current_timestamp),
('Semiconductors', current_timestamp, current_timestamp),
('Social Issues', current_timestamp, current_timestamp),
('Social Psychology', current_timestamp, current_timestamp),
('Social Sciences', current_timestamp, current_timestamp),
('Social Work', current_timestamp, current_timestamp),
('Sociolinguistics', current_timestamp, current_timestamp),
('Sociology of Education', current_timestamp, current_timestamp),
('Sociology of Law', current_timestamp, current_timestamp),
('Sociology', current_timestamp, current_timestamp),
('Software Engineering', current_timestamp, current_timestamp),
('Soil Sciences', current_timestamp, current_timestamp),
('Solar Terrestrial Physics', current_timestamp, current_timestamp),
('Special Education', current_timestamp, current_timestamp),
('Sports and Recreation', current_timestamp, current_timestamp),
('Stars', current_timestamp, current_timestamp),
('Statistical Physics', current_timestamp, current_timestamp),
('Statistics', current_timestamp, current_timestamp),
('Stereochemistry', current_timestamp, current_timestamp),
('Surface and Interface Physics', current_timestamp, current_timestamp),
('Surgery', current_timestamp, current_timestamp),
('Syntax', current_timestamp, current_timestamp),
('Systems and Control Theory', current_timestamp, current_timestamp),
('Taxation Law', current_timestamp, current_timestamp),
('Taxation', current_timestamp, current_timestamp),
('Teacher Education', current_timestamp, current_timestamp),
('Technological Change', current_timestamp, current_timestamp),
('Telecommunications', current_timestamp, current_timestamp),
('Testing and Evaluation', current_timestamp, current_timestamp),
('Testing', current_timestamp, current_timestamp),
('The Sun', current_timestamp, current_timestamp),
('Theology', current_timestamp, current_timestamp),
('Theoretical Astrophysics', current_timestamp, current_timestamp),
('Theoretical Chemistry', current_timestamp, current_timestamp),
('Theoretical Linguistics', current_timestamp, current_timestamp),
('Thermodynamics', current_timestamp, current_timestamp),
('Topology', current_timestamp, current_timestamp),
('Tourism', current_timestamp, current_timestamp),
('Toxicology', current_timestamp, current_timestamp),
('Transpersonal Psychology', current_timestamp, current_timestamp),
('Transport Law', current_timestamp, current_timestamp),
('Tropical', current_timestamp, current_timestamp),
('Urban Economics', current_timestamp, current_timestamp),
('Vehicular Technology', current_timestamp, current_timestamp),
('Veterinary Science', current_timestamp, current_timestamp),
('Virology', current_timestamp, current_timestamp),
('Visual and Performing Arts', current_timestamp, current_timestamp),
('Volcanism', current_timestamp, current_timestamp),
('Welding', current_timestamp, current_timestamp),
('Wireless and Mobile Communication', current_timestamp, current_timestamp),
('Wood', current_timestamp, current_timestamp),
('Zoology and Animal Science', current_timestamp, current_timestamp);"
